test("foo", () => {
  fail(1)
})
